body_acc_x_test<-read.csv("UCI HAR Dataset/test/Inertial Signals/body_acc_x_test.txt", sep="", header = FALSE, strip.white=TRUE)
body_acc_y_test<-read.csv("UCI HAR Dataset/test/Inertial Signals/body_acc_y_test.txt", sep="", header = FALSE, strip.white=TRUE)
body_acc_z_test<-read.csv("UCI HAR Dataset/test/Inertial Signals/body_acc_z_test.txt", sep="", header = FALSE, strip.white=TRUE)
body_gyro_x_test<-read.csv("UCI HAR Dataset/test/Inertial Signals/body_gyro_x_test.txt", sep="", header = FALSE, strip.white=TRUE)
body_gyro_y_test<-read.csv("UCI HAR Dataset/test/Inertial Signals/body_gyro_y_test.txt", sep="", header = FALSE, strip.white=TRUE)
body_gyro_z_test<-read.csv("UCI HAR Dataset/test/Inertial Signals/body_gyro_z_test.txt", sep="", header = FALSE, strip.white=TRUE)
total_acc_x_test<-read.csv("UCI HAR Dataset/test/Inertial Signals/total_acc_x_test.txt", sep="", header = FALSE, strip.white=TRUE)
total_acc_y_test<-read.csv("UCI HAR Dataset/test/Inertial Signals/total_acc_y_test.txt", sep="", header = FALSE, strip.white=TRUE)
total_acc_z_test<-read.csv("UCI HAR Dataset/test/Inertial Signals/total_acc_z_test.txt", sep="", header = FALSE, strip.white=TRUE)

